## Importações das Bibliotecas

In [3]:
# ---
# Instalando bibliotecas (primeira vez)

#!pip install numpy
#!pip install pandas
#!pip install sentence_transformers
#!pip install sklearn_metrics_pairwise

# ---

In [2]:
# ---
import os
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
# ---

/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Arquivos dos Quoruns

In [15]:
def load_documents(path):
    documents = []
    ids = []

    for file in os.listdir(path):
        if file.endswith(".txt"):
            with open(os.path.join(path, file), "r", encoding="utf-8") as f:
                text = f.read()
                documents.append(text)
                ids.append(file.replace(".txt", ""))

    return ids, documents

## Pré-processamento (normalização dos textos)

In [16]:
def preprocess(text):
    text = text.lower()
    text = text.strip()
    return text

## Gerar Embeddings

In [17]:
def generate_embeddings(texts, model_name):
    model = SentenceTransformer(model_name)
    embeddings = model.encode(texts)
    return embeddings

## Calcular Matriz de Similaridade

In [18]:
def compute_similarity(embeddings):
    sim_matrix = cosine_similarity(embeddings)
    return sim_matrix

## Criação de DataFrame

In [19]:
def create_similarity_dataframe(ids, sim_matrix):
    df = pd.DataFrame(sim_matrix, index=ids, columns=ids)
    return df

## Salvar Resultados

In [20]:
def save_outputs(model, embeddings, sim_df):
    np.save(f"..//..//Results//Embeddings/embeddings_{model}.npy", embeddings)
    sim_df.to_csv(f"..//..//Results/Similarity/similarity_matrix_{model}.csv")

## Função Main (principal)

In [ ]:
'''
def main():
    ids, documents = load_documents("..//..//Data//Data Ready//Law//Quórum - Municipal Law")
    
    documents = [preprocess(doc) for doc in documents]

    model_1 = "paraphrase-multilingual-MiniLM-L12-v2"
    model_2 = "distiluse-base-multilingual-cased-v2"
    model_3 = "paraphrase-multilingual-mpnet-base-v2"
    embeddings = generate_embeddings(documents, model_1)

    sim_matrix = compute_similarity(embeddings)

    sim_df = create_similarity_dataframe(ids, sim_matrix)

    #save_outputs(ids, embeddings, sim_df)

if __name__ == "__main__":
    main()
'''

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4060.18it/s]

In [27]:
# Modelo 1

ids, documents = load_documents("..//..//Data//Data Ready//Law//Quórum - Municipal Law")
    
documents = [preprocess(doc) for doc in documents]

model_1 = "paraphrase-multilingual-MiniLM-L12-v2"
embeddings_1 = generate_embeddings(documents, model_1)

sim_matrix_1 = compute_similarity(embeddings_1)

sim_df_1 = create_similarity_dataframe(ids, sim_matrix_1)

save_outputs(1, embeddings_1, sim_df_1)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 754.64it/s]

In [28]:
# Modelo 2

ids, documents = load_documents("..//..//Data//Data Ready//Law//Quórum - Municipal Law")
    
documents = [preprocess(doc) for doc in documents]

model_2 = "distiluse-base-multilingual-cased-v2"
embeddings_2 = generate_embeddings(documents, model_2)

sim_matrix_2 = compute_similarity(embeddings_2)

sim_df_2 = create_similarity_dataframe(ids, sim_matrix_2)

save_outputs(2, embeddings_2, sim_df_2)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 697.27it/s]

In [29]:
# Modelo 3

ids, documents = load_documents("..//..//Data//Data Ready//Law//Quórum - Municipal Law")
    
documents = [preprocess(doc) for doc in documents]

model_3 = "paraphrase-multilingual-mpnet-base-v2"
embeddings_3 = generate_embeddings(documents, model_3)

sim_matrix_3 = compute_similarity(embeddings_3)

sim_df_3 = create_similarity_dataframe(ids, sim_matrix_3)

save_outputs(3, embeddings_3, sim_df_3)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 492.39it/s]

## Validação do Modelo

In [24]:
test_ids = ["maioria absoluta", "metade mais um"]
test_embeddings_1 = generate_embeddings(test_ids, model_3)

test_sim_matrix_1 = compute_similarity(test_embeddings_1)

test_sim_df_1 = df = pd.DataFrame(test_sim_matrix_1, index=test_ids, columns=test_ids)
test_sim_df_1

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3918.33it/s]

                  maioria absoluta  metade mais um
maioria absoluta          1.000000        0.311638
metade mais um            0.311638        1.000000

In [26]:
test_ids = ["dois terços", "2/3"]
test_model_1 = "paraphrase-multilingual-MiniLM-L12-v2"
test_embeddings_1 = generate_embeddings(test_ids, model_3)

test_sim_matrix_1 = compute_similarity(test_embeddings_1)

test_sim_df_1 = df = pd.DataFrame(test_sim_matrix_1, index=test_ids, columns=test_ids)
test_sim_df_1

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 10040.50it/s]

             dois terços       2/3
dois terços     1.000000  0.905602
2/3             0.905602  1.000000

In [28]:
test_ids = ["maioria simples", "dois terços"]
test_model_1 = "paraphrase-multilingual-MiniLM-L12-v2"
test_embeddings_1 = generate_embeddings(test_ids, model_3)

test_sim_matrix_1 = compute_similarity(test_embeddings_1)

test_sim_df_1 = df = pd.DataFrame(test_sim_matrix_1, index=test_ids, columns=test_ids)
test_sim_df_1

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7447.92it/s]

                 maioria simples  dois terços
maioria simples         1.000000     0.546975
dois terços             0.546975     1.000000